version: '3.1'

services:
  pi-hole:
    container_name: pi-hole
    image: pihole/pihole
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '8080:80/tcp'
      - '443:443/tcp'
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
    volumes:
      - './pi-hole/etc-pihole/:/etc/pihole/'
      - './pi-hole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server
    environment:
      ROCKET_TLS: '{certs="/ssl/bitwarden.crt",key="/ssl/bitwarden.key"}' 
    ports:
      - '8200:80'
    volumes:
      - 'vaultwarden_data:/data/'
      - './bitwarden/config/:/config'
      - './bitwarden/certificates/:/ssl/'
    restart: unless-stopped

  # Documentation: <https://docs.miguelndecarvalho.pt/projects/speedtest-exporter>
  speedtest:
    container_name: speedtest
    image: miguelndecarvalho/speedtest-exporter
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - 'prometheus_data:/prometheus'
      - './prometheus/:/etc/prometheus/'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=90d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - 'grafana_data:/var/lib/grafana'
      - './grafana/provisioning/:/etc/grafana/provisioning/'
    ports:
      - '3000:3000'
    restart: unless-stopped

  cadvisor:
    image: cadvisor
    container_name: cadvisor
    command: --raw_cgroup_prefix_whitelist=/docker/
    build:
      context: cadvisor
    privileged: true
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
    devices:
      - '/dev/kmsg:/dev/kmsg'
    restart: unless-stopped

volumes:
  vaultwarden_data:
  grafana_data:
  prometheus_data:
