global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'Alertmanager'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'speedtest'
    metrics_path: /metrics
    scrape_interval: 15m
    scrape_timeout: 60s
    static_configs:
      - targets: ['speedtest:9798']

  - job_name: 'node'
    metrics_path: /metrics
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'cadvisor'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
